[package]
name = "neura-studios/recombee-luau-sdk"
description = "A Luau SDK for use with the Recombee recommendation engine."
version = "1.1.4"
license = "MIT"
authors = ["Juniper Hovey"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/*", "vendor", "vendor/**", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
gt = "corecii/greentea@0.4.7"
HashLib = "boatbomber/hashlib@1.0.0"
Signal = "sleitnick/signal@2.0.1"